package common.dto;

public enum RequestType {
    // existing
    PING,
    GET_ORDER,
    UPDATE_ORDER,
    INSERT_ORDER,
    SUBSCRIBE,
    UNSUBSCRIBE,

    // auth
    LOGIN_STAFF,
    LOGIN_VISITOR,
    LOGOUT,
    REGISTER_SUBSCRIBER,
    REGISTER_GUIDE,

    // reservations
    CREATE_RESERVATION,
    GET_RESERVATION,
    UPDATE_RESERVATION,
    CANCEL_RESERVATION,
    LIST_RESERVATIONS,
    CONFIRM_RESERVATION,
    JOIN_WAITLIST,
    LEAVE_WAITLIST,
    ACCEPT_GRAB,

    // parks
    GET_PARK,
    LIST_PARKS,
    REQUEST_PARAM_CHANGE,
    LIST_PENDING_CHANGES,
    APPROVE_PARAM_CHANGE,
    REJECT_PARAM_CHANGE,
    CHECK_AVAILABILITY,

    // visits
    ENTER_VISIT,
    EXIT_VISIT,
    CASUAL_VISIT,
    CURRENT_OCCUPANCY,

    // reports
    REPORT_VISITS_BY_TYPE,
    REPORT_CANCELLATIONS,

    // notifications
    LIST_NOTIFICATIONS,
    ACK_NOTIFICATION
}
