package common.dto;

public enum RequestType {
    PING,
    LOGIN,
    LIST_PARKS,
    CREATE_RESERVATION,
    GET_RESERVATION,
    UPDATE_RESERVATION,
    CANCEL_RESERVATION,
    ENTER_PARK,
    EXIT_PARK,
    GENERATE_VISITS_REPORT,
    GENERATE_USAGE_REPORT,
    GENERATE_CANCELLATIONS_REPORT
}
